name: Generate Terraform Plugin Documentation

on:
  push:
    branches:
      - main
      - stable-*

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Go dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.GOPATH }}/pkg/mod
          key: go-${{ hashFiles('**/*.go') }}
        restore-keys: |
          go-

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Install tfplugindocs
        run: go get github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@latest

      - name: Generate documentation
        run: make generatedocs
